import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { swaggerUi, swaggerDocs } from './swagger';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* Swagger UI */}
        <script>
          {`
            const express = require('express');
            const app = express();
            app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocs));
          `}
        </script>
      </body>
    </html>
  )
}
